import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Layout from "layout/Layout";
import BoardList from "components/board-list";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <BoardList title="Recently viewed" />
          <BoardList title="process" />
        </main>
      </Layout>
    </div>
  );
};

export default Home;
